### ISSUE TITLE
Summarize this Case

### ISSUE THREAD

**Issue by stephbuon** [stephbuon/democracy-lab#170]
Summarize this case in 2 paragraphs: https://api.parliament.uk/historic-hansard/commons/1824/jun/01/motion-respecting-the-trial-and

**Comment by palmerbradshaw** [comment]
[Week 5 Deliverable.docx](https://github.com/stephbuon/democracy-lab/files/9637346/Week.5.Deliverable.docx)

**Comment by stephbuon** [comment]
@palmerbradshaw I just realized only Mrs. Walrand is in this case.
